# Dockerfile.backend (VERSIÓN CORRECTA)
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY server.js ./
COPY serviceAccountKey.json ./

EXPOSE 4000

CMD ["node", "server.js"]